-- Calculating REVENUE
SELECT
	ORDER_ID,
	SUM(MEAL_PRICE * ORDER_QUANTITY) AS REVENUE
FROM
	ORDERS
	JOIN MEALS USING (MEAL_ID)
GROUP BY
	ORDER_ID
ORDER BY
	ORDER_ID
	
	
-- Calculating Cost
SELECT
	MEAL_ID,
	SUM(MEAL_COST * STOCKED_QUANTITY) AS TOTAL_COST
FROM
	MEALS
	JOIN STOCK USING (MEAL_ID)
GROUP BY
	MEAL_ID
ORDER BY
	TOTAL_COST DESC

	
-- Using Common Table Expression
WITH
	COSTS_AND_QUANTITES AS (
		SELECT
			M.MEAL_ID,
			S.STOCKED_QUANTITY AS QUANTITY,
			SUM(M.MEAL_COST * S.STOCKED_QUANTITY) AS COST
		FROM
			MEALS AS M
			JOIN STOCK AS S USING (MEAL_ID)
		GROUP BY
			M.MEAL_ID,
			S.STOCKED_QUANTITY
	)
SELECT
	*
FROM
	COSTS_AND_QUANTITES
ORDER BY COST DESC
LIMIT 3;