-- JOIN without alias
SELECT
	PRESIDENT,
	PRIME_MINISTER
FROM
	PRESIDENTS
	INNER JOIN PRIME_MINISTERS 
	ON PRESIDENTS.COUNTRY = PRIME_MINISTERS.COUNTRY;
	
-- Join query with using clause
SELECT
	PR.PRESIDENT,
	PM.PRIME_MINISTER
FROM
	PRESIDENTS AS PR
	INNER JOIN PRIME_MINISTERS AS PM USING (COUNTRY);

-- 
SELECT
	S.COUNTRY,
	S.CONTINENT,
	INDEP_YEAR MONARCH
FROM
	MONARCHS
	INNER JOIN STATES AS S USING (COUNTRY);
	
-- INNER JOIN USING ON
SELECT
	PR.PRESIDENT,
	PM.PRIME_MINISTER,
	PM.COUNTRY,
	PM.CONTINENT
FROM
	PRESIDENTS AS PR
INNER JOIN PRIME_MINISTERS AS PM 
ON PM.COUNTRY = PR.COUNTRY;

-- Multiple INNER JOIN
SELECT
	PM.COUNTRY,
	PM.CONTINENT,
	PR.PRESIDENT,
	PM.PRIME_MINISTER,
	PMT.PM_START
FROM
	PRESIDENTS AS PR
INNER JOIN PRIME_MINISTERS AS PM 
ON PM.COUNTRY = PR.COUNTRY
INNER JOIN PRIME_MINISTER_TERMS AS PMT 
ON PMT.PRIME_MINISTER = PM.PRIME_MINISTER;

-- JOIN ON MULTIPLE KEYS
SELECT
	*
FROM
	MONARCHS AS M
	INNER JOIN STATES AS S ON M.COUNTRY = S.COUNTRY
	AND S.CONTINENT = S.CONTINENT;