SELECT
	*
FROM
	MONARCHS;

-- Join query with using clause
SELECT
	PR.PRESIDENT,
	PM.PRIME_MINISTER
FROM
	PRESIDENTS AS PR
	INNER JOIN PRIME_MINISTERS AS PM USING (COUNTRY)
	
-- INNER JOIN USING ON
SELECT
	PR.PRESIDENT,
	PM.PRIME_MINISTER,
	PM.COUNTRY,
	PM.CONTINENT
FROM
	PRESIDENTS AS PR
INNER JOIN PRIME_MINISTERS AS PM 
ON PM.COUNTRY = PR.COUNTRY